name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & Build
        run: |
          yarn install
          yarn run test
          ls -l dist/
      - name: Debug working directory
        run: |
          pwd
          ls -l
          ls -l dist/
      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.HOST }}
          pass: ${{ secrets.PASSWORD }}
          user: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          first_ssh: |
            rm -rf /home/pages/admin
            ls -la 
            echo $WELCOME 
            mkdir -p /home/test
          scp: |-
            './dist/*' => /home/pages/admin
          last_ssh: |
            echo $LASTSSH 
            ls -la