name: Build and Deploy
on:
  push:
    branches:
      - 'release/**'
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_now=$(TZ='Asia/Shanghai'  date +'%F-%H-%M-%S')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install & Build
        run: |
          yarn install
          yarn run build
          ls -l dist/
      - name: Debug working directory
        run: |
          pwd
          ls -l
          ls -l dist/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repository_name }}-${{ env.date_now }}
          path: dist/
          retention-days: 7
        